templateDir: ansible

files:

# Example JSON file using Ansible value providers
- file: output.json
  template: output.json.hbs

# Example for decrypting and copying a file
- file: decrypted-file.yaml
  url: ansible-vault:vault/test-encrypted.yml


config:
  password1:
  password2:
  password3:

sensitiveConfigParameters:
- password1
- password2
- password3
