templateDir: ansible

files:

- file: output.json
  template: output.json.hbs


config:
  password1: ${ansible-vault::pwd1}
  password2: ${ansible-vault::group1.pwd2}
  password3: ${ansible-vault::group1.pwd3}
